Sprint1 - FULL
aldaitzwild/LYO-php-March2021-pjt3-Eventoo pull request #13
Opened 2021-06-02 21:10 UTC by Bachir-Ndiaye

=> Merged all classmates work
=> Added some CSS on diary page to fit the figma model
=> made a dataset for the presentation

2021-06-03 07:19 UTC, Bachir-Ndiaye commented
Resolved conflicts

2021-06-03 07:21 UTC, aldaitzwild requested changes

2021-06-03 07:21 UTC, aldaitzwild commented on yarn.lock
> +>>>>>>> dev
Unsolved conflicts

2021-06-03 07:21 UTC, aldaitzwild commented on yarn.lock
> +=======
Unsolved conflicts

2021-06-04 07:50 UTC, aldaitzwild requested changes
Conflicts with dev

2021-06-04 08:25 UTC, closed without merging